### ISSUE TITLE
Sometimes cannot correctly show condidates

### ISSUE THREAD

**Issue by BooAA** [muffinmad/emacs-completions-frame#1]
As title, I find sometimes completions-frame-mode cannot display whole frame correctly. See GIF  below:

Emacs version: Emacs 28, commit: 8700319109c06932cd66615c85fc21e386b40df6
OS, DE: Debian/testing, Cinnamon
![Peek 2020-11-16 00-39](https://user-images.githubusercontent.com/32809182/99191043-090f0b00-27a5-11eb-921b-e3799ebd5b39.gif)

As in the GIF, sometimes only incomplete modeline and part of help message in \*completion\* buffer are shown.

**Comment by muffinmad** [comment]
Liangjie Lee <notifications@github.com> writes:

> As title, I find sometimes completions-frame-mode cannot display whole frame correctly. See GIF  below:

Does having this in the `init.el` helps?

```elisp
(setq x-gtk-resize-child-frames 'resize-mode)
```

**Comment by BooAA** [comment]
> ```elisp
> (setq x-gtk-resize-child-frames 'resize-mode)
> ```

Doesn't work for me. It seems that child frame do resize to proper size, but the content (buffer) it displays isn't fully shown.

**Comment by muffinmad** [comment]
> Doesn't work for me. It seems that child frame do resize to proper size, but the content (buffer) it displays isn't fully shown.

Indeed. Didn't see this on Emacs 27 but see this on recent master GTK build.

**Comment by muffinmad** [comment]
Looks like Emacs 27 has this bug too. Can you please check:
1. `emacs -Q`
2. Paste this code:
```elisp
(setq x-gtk-resize-child-frames 'resize-mode)
(defvar cf-frame (make-frame `((parent-frame . ,(selected-frame))
                               (width . 20)
                               (background-color . "#cccccc"))))
(progn
  (modify-frame-parameters cf-frame '((height . 10)))
  (modify-frame-parameters cf-frame '((height . 30))))
```
3. `M-x eval-buffer`
Window is smaller than child frame.
4. Repeat `M-x eval-buffer` several times.
Child frame changes it height from 10 to 30 and vice versa.

**Comment by BooAA** [comment]
8d20496 works for me, thanks.
