### ISSUE TITLE
Bindings for completion selection

### ISSUE THREAD

**Issue by sirikid** [muffinmad/emacs-completions-frame#2]
First of all, I want to thank you for your work. Nice mode, it helps a lot.

How can I call functions in that frame? I want to define something like this (oversimplified):
```elisp
(defun cfm-next-completion ()
  (with-current-buffer "*Completions*"
    (next-completion 1)))
```
But this does not work.

**Comment by sirikid** [comment]
Update: the snippet below works with `next`/`previous-completion`, but I still have troubles with `choose-completion`.
```elisp
(with-current-buffer "*Completions*"
  (with-selected-frame completions-frame-frame
    ...))
  ```

**Comment by muffinmad** [comment]
I'm sorry, I was really sure that I've replied to this. I'm even remember how I wrote the code for this :)

Anyway, try the followind:

```elisp
(defun cfm-next-completion ()
  (interactive)
  (with-selected-frame completions-frame-frame
    (next-completion 1)))

(defun cfm-prev-completion ()
  (interactive)
  (with-selected-frame completions-frame-frame
    (next-completion -1)))

(defun cfm-accept-completion ()
  (interactive)
  (with-selected-frame completions-frame-frame
    (choose-completion)))

(global-set-key (kbd "C-c n") #'cfm-next-completion)
(global-set-key (kbd "C-c p") #'cfm-prev-completion)
(global-set-key (kbd "C-c RET") #'cfm-accept-completion)
```

Hope it helps and, again, sorry for the late reply.

**Comment by sirikid** [comment]
Yeah, it works, thanks.

**Comment by muffinmad** [comment]
Hi @sirikid !
JFYI I've added keymap to navigate and accept completions here https://github.com/muffinmad/emacs-completions-frame/commit/7353edb6e6df3d1a45f4fd7899e34ecfe6217e13
